{% set name = "tensorboard-plugin-wit" %}
{% set version = "1.6.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/41/ec/3da49289b93963bd8b32d29ed108f1809436ff3d9cd4e29c90bac4a7292f/tensorboard_plugin_wit-1.6.0.post2-py3-none-any.whl
  sha256: 2154662accfef72c9ac52bddf6cb89ecb35d61cd1092f6e5313d8eb2f34465ad
 
build:
  noarch: python
  number: 1
  script: "python -m pip install tensorboard_plugin_wit-{{ version }}*.whl --no-deps --ignore-installed -vv "
  entry_points:
    - wit = tensorboard_plugin_wit.wit_plugin_loader:WhatIfToolPluginLoader

requirements:
  host:
    - pip
    - python  # noarch package; don't tie to specific python version
  run:
    - python  # noarch package; don't tie to specific python version

test:
  imports:
    - tensorboard_plugin_wit

about:
  description: |
      What-If Tool TensorBoard plugin. 
  dev_url: https://github.com/PAIR-code/what-if-tool
  doc_url: https://github.com/PAIR-code/what-if-tool
  home: https://pair-code.github.io/what-if-tool
  license: Apache License 2.0
  license_family: Apache
  license_file: LICENSE
  summary: What-If Tool TensorBoard plugin.

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
